-- =============================================================================
-- Conversational Data Analyst — schema for port & terminal operations
-- See docs/ADR/ADR-001-domain-and-data-model.md
--
-- IMPORTANT: the COMMENT ON statements at the bottom of this file are functional,
-- not decorative. src/schema.py introspects them and injects them into the
-- SQL-generation prompt as schema context (ADR-003). They are how the model learns
-- units, enum values, and the meaning of near-identical timestamp columns. Treat
-- them as production code: if you change a column, change its comment.
--
-- Timestamps are `timestamp without time zone`, deliberately. Terminal operations
-- are reasoned about in local port time, and — critically — timestamptz arithmetic
-- is only STABLE, not IMMUTABLE, which would make the generated column below
-- illegal. See the note on berth_wait_hours.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Dimension: terminals
-- ---------------------------------------------------------------------------
CREATE TABLE terminals (
    terminal_id   integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    terminal_name text         NOT NULL,
    port_name     text         NOT NULL,
    country       text         NOT NULL,
    berth_count   smallint     NOT NULL,
    opened_year   smallint     NOT NULL,
    CONSTRAINT terminals_name_unique     UNIQUE (terminal_name),
    CONSTRAINT terminals_berth_count_chk CHECK (berth_count BETWEEN 1 AND 30),
    CONSTRAINT terminals_opened_year_chk CHECK (opened_year BETWEEN 1900 AND 2100)
);

-- ---------------------------------------------------------------------------
-- Dimension: vessels
-- ---------------------------------------------------------------------------
CREATE TABLE vessels (
    vessel_id    integer  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vessel_name  text     NOT NULL,
    imo_number   char(7)  NOT NULL,
    vessel_type  text     NOT NULL,
    capacity_teu integer  NOT NULL,
    operator     text     NOT NULL,
    flag_country text     NOT NULL,
    year_built   smallint NOT NULL,
    CONSTRAINT vessels_imo_unique      UNIQUE (imo_number),
    CONSTRAINT vessels_type_chk        CHECK (vessel_type IN
                                        ('Container Ship', 'Bulk Carrier', 'Ro-Ro', 'Tanker')),
    CONSTRAINT vessels_capacity_chk    CHECK (capacity_teu > 0),
    CONSTRAINT vessels_year_built_chk  CHECK (year_built BETWEEN 1950 AND 2100)
);

-- ---------------------------------------------------------------------------
-- Dimension: cranes (equipment, owned by exactly one terminal)
-- ---------------------------------------------------------------------------
CREATE TABLE cranes (
    crane_id          integer  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    terminal_id       integer  NOT NULL,
    crane_code        text     NOT NULL,
    model             text     NOT NULL,
    commissioned_date date     NOT NULL,
    max_lift_tonnes   smallint NOT NULL,
    status            text     NOT NULL,
    CONSTRAINT cranes_terminal_fk   FOREIGN KEY (terminal_id)
                                    REFERENCES terminals (terminal_id),
    CONSTRAINT cranes_code_unique   UNIQUE (crane_code),
    CONSTRAINT cranes_status_chk    CHECK (status IN ('active', 'maintenance', 'retired')),
    CONSTRAINT cranes_max_lift_chk  CHECK (max_lift_tonnes > 0)
);

-- ---------------------------------------------------------------------------
-- Fact: port_calls — one row per vessel visit to a terminal
-- ---------------------------------------------------------------------------
CREATE TABLE port_calls (
    port_call_id integer   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vessel_id    integer   NOT NULL,
    terminal_id  integer   NOT NULL,
    arrival_ts   timestamp NOT NULL,
    berth_ts     timestamp,
    departure_ts timestamp,
    status       text      NOT NULL,

    -- Hours spent waiting at anchor between arriving in the port area and being
    -- allocated a berth. This is THE congestion metric for the domain.
    --
    -- STORED is specified explicitly because PostgreSQL 18 changed the default kind of
    -- generated column to VIRTUAL. Omitting it here would silently produce a virtual
    -- column, which cannot be indexed.
    -- (https://www.postgresql.org/docs/18/ddl-generated-columns.html)
    --
    -- The expression is legal only because these are `timestamp` not `timestamptz`
    -- columns: timestamp subtraction is IMMUTABLE, whereas the timestamptz equivalent
    -- is STABLE and generation expressions may only use immutable functions.
    berth_wait_hours numeric(10, 2)
        GENERATED ALWAYS AS (EXTRACT(EPOCH FROM (berth_ts - arrival_ts)) / 3600.0) STORED,

    CONSTRAINT port_calls_vessel_fk   FOREIGN KEY (vessel_id)   REFERENCES vessels (vessel_id),
    CONSTRAINT port_calls_terminal_fk FOREIGN KEY (terminal_id) REFERENCES terminals (terminal_id),
    CONSTRAINT port_calls_status_chk  CHECK (status IN ('completed', 'cancelled')),
    -- NULL-tolerant by design: a cancelled call never berths, so berth_ts and
    -- departure_ts are NULL and these comparisons evaluate to NULL, which passes.
    CONSTRAINT port_calls_berth_after_arrival_chk   CHECK (berth_ts     >= arrival_ts),
    CONSTRAINT port_calls_depart_after_berth_chk    CHECK (departure_ts >= berth_ts),
    -- A completed call must have both timestamps; a cancelled one must have neither.
    CONSTRAINT port_calls_status_consistency_chk CHECK (
        (status = 'completed' AND berth_ts IS NOT NULL AND departure_ts IS NOT NULL)
        OR
        (status = 'cancelled' AND berth_ts IS NULL AND departure_ts IS NULL)
    )
);

-- ---------------------------------------------------------------------------
-- Fact: cargo_moves — one row per crane move batch within a port call
-- ---------------------------------------------------------------------------
CREATE TABLE cargo_moves (
    move_id          integer   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    port_call_id     integer   NOT NULL,
    crane_id         integer   NOT NULL,
    move_type        text      NOT NULL,
    container_count  integer   NOT NULL,
    move_ts          timestamp NOT NULL,
    duration_minutes smallint  NOT NULL,
    CONSTRAINT cargo_moves_port_call_fk FOREIGN KEY (port_call_id)
                                        REFERENCES port_calls (port_call_id),
    CONSTRAINT cargo_moves_crane_fk     FOREIGN KEY (crane_id) REFERENCES cranes (crane_id),
    CONSTRAINT cargo_moves_type_chk     CHECK (move_type IN ('load', 'discharge')),
    CONSTRAINT cargo_moves_count_chk    CHECK (container_count > 0),
    CONSTRAINT cargo_moves_duration_chk CHECK (duration_minutes > 0)
);

-- ---------------------------------------------------------------------------
-- Indexes: foreign keys (PostgreSQL does not create these automatically) and the
-- timestamp columns used for time-series grouping.
-- ---------------------------------------------------------------------------
CREATE INDEX cranes_terminal_idx          ON cranes      (terminal_id);
CREATE INDEX port_calls_vessel_idx        ON port_calls  (vessel_id);
CREATE INDEX port_calls_terminal_idx      ON port_calls  (terminal_id);
CREATE INDEX port_calls_arrival_ts_idx    ON port_calls  (arrival_ts);
CREATE INDEX port_calls_terminal_time_idx ON port_calls  (terminal_id, arrival_ts);
CREATE INDEX cargo_moves_port_call_idx    ON cargo_moves (port_call_id);
CREATE INDEX cargo_moves_crane_idx        ON cargo_moves (crane_id);
CREATE INDEX cargo_moves_move_ts_idx      ON cargo_moves (move_ts);

-- =============================================================================
-- Schema documentation. Read by src/schema.py and injected into the LLM prompt.
-- Every comment states units, allowed values, and grain, because those are exactly
-- the facts a column type cannot express and a wrong assumption about them produces
-- SQL that runs and returns the wrong number.
-- =============================================================================

COMMENT ON TABLE terminals IS
  'Container terminals. One row per terminal. A port may contain several terminals.';
COMMENT ON COLUMN terminals.terminal_name IS 'Terminal name, unique across all ports.';
COMMENT ON COLUMN terminals.port_name     IS 'Port the terminal belongs to, e.g. Rotterdam, Singapore.';
COMMENT ON COLUMN terminals.country       IS 'Country the port is located in.';
COMMENT ON COLUMN terminals.berth_count   IS 'Number of berths available at this terminal (capacity proxy).';
COMMENT ON COLUMN terminals.opened_year   IS 'Calendar year the terminal opened.';

COMMENT ON TABLE vessels IS
  'Ships that call at the terminals. One row per vessel.';
COMMENT ON COLUMN vessels.vessel_name  IS 'Ship name. Not guaranteed unique; use vessel_id to identify a vessel.';
COMMENT ON COLUMN vessels.imo_number   IS 'IMO registration number, exactly 7 digits, unique per vessel.';
COMMENT ON COLUMN vessels.vessel_type  IS 'One of: Container Ship, Bulk Carrier, Ro-Ro, Tanker.';
COMMENT ON COLUMN vessels.capacity_teu IS 'Maximum capacity in TEU (twenty-foot equivalent units). Capacity, NOT actual cargo carried.';
COMMENT ON COLUMN vessels.operator     IS 'Shipping line operating the vessel. Use this column for questions about carriers, lines, or operators.';
COMMENT ON COLUMN vessels.flag_country IS 'Country of registration (flag state).';
COMMENT ON COLUMN vessels.year_built   IS 'Calendar year the vessel was built.';

COMMENT ON TABLE cranes IS
  'Quay cranes. One row per crane. Each crane belongs to exactly one terminal and can only service vessels berthed at that terminal.';
COMMENT ON COLUMN cranes.terminal_id       IS 'Terminal that owns this crane. A crane never works at another terminal.';
COMMENT ON COLUMN cranes.crane_code        IS 'Short operational identifier, unique across terminals, e.g. RTM-QC-03.';
COMMENT ON COLUMN cranes.model             IS 'Manufacturer model designation.';
COMMENT ON COLUMN cranes.commissioned_date IS 'Date the crane entered service. Use for questions about crane age.';
COMMENT ON COLUMN cranes.max_lift_tonnes   IS 'Maximum safe working load in tonnes.';
COMMENT ON COLUMN cranes.status            IS 'One of: active, maintenance, retired.';

COMMENT ON TABLE port_calls IS
  'Vessel visits. One row per visit of a vessel to a terminal. This is the grain for berth wait, dwell time and visit-count questions.';
COMMENT ON COLUMN port_calls.vessel_id    IS 'Vessel making the call. Join to vessels for operator, type or capacity.';
COMMENT ON COLUMN port_calls.terminal_id  IS 'Terminal being visited. Join to terminals for port or country.';
COMMENT ON COLUMN port_calls.arrival_ts   IS 'When the vessel arrived in the port area and began waiting for a berth.';
COMMENT ON COLUMN port_calls.berth_ts     IS 'When the vessel was allocated a berth and cargo work could begin. NULL for cancelled calls.';
COMMENT ON COLUMN port_calls.departure_ts IS 'When the vessel left the berth. NULL for cancelled calls.';
COMMENT ON COLUMN port_calls.status       IS 'One of: completed, cancelled. Cancelled calls never berthed and have NULL berth_ts, departure_ts and berth_wait_hours.';
COMMENT ON COLUMN port_calls.berth_wait_hours IS
  'HOURS waited at anchor between arrival_ts and berth_ts, computed automatically. This is the standard congestion metric: use AVG(berth_wait_hours) for "average waiting time" questions. NULL for cancelled calls, so AVG ignores them.';

COMMENT ON TABLE cargo_moves IS
  'Container handling activity. One row per batch of container moves performed by one crane during one port call. Finer grain than port_calls: a single port call has many cargo_moves rows.';
COMMENT ON COLUMN cargo_moves.port_call_id     IS 'Port call this work belongs to. Join to port_calls for vessel, terminal and timing.';
COMMENT ON COLUMN cargo_moves.crane_id         IS 'Crane that performed the moves. Always belongs to the same terminal as the port call.';
COMMENT ON COLUMN cargo_moves.move_type        IS 'One of: load (containers onto the vessel), discharge (containers off the vessel).';
COMMENT ON COLUMN cargo_moves.container_count  IS 'Number of containers moved in this batch. SUM this column for throughput or volume questions.';
COMMENT ON COLUMN cargo_moves.move_ts          IS 'When this batch of moves was performed.';
COMMENT ON COLUMN cargo_moves.duration_minutes IS 'MINUTES taken to complete the batch. Crane productivity = container_count / (duration_minutes / 60.0) moves per hour.';
